# Generated by Django 3.1 on 2020-10-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=55)),
                ('lastName', models.CharField(max_length=55)),
                ('avatar', models.ImageField(upload_to='images/')),
                ('organization', models.CharField(max_length=100)),
                ('techSkills', models.TextField()),
                ('courseWork', models.TextField()),
                ('gitRepo', models.URLField()),
                ('linkedIn', models.URLField()),
                ('twitter', models.URLField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
